# Copyright (c) 2021 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

status = [
  # GitHub actions
  "github/linux/debug/fast",
  "github/linux/fetchcontent/fast",
  "github/linux/hip/fast",
  "github/linux/sanitizers/fast",
  "github/linux/tracy/fast",
  "github/macos/debug/core",
  "github/macos/debug/tests/examples_regressions",
  "github/macos/debug/tests/performance",
  "github/macos/debug/tests/unit",
  "github/macos/debug/tests/unit/algorithms",
  "github/macos/debug/tests/unit/container_algorithms",
  "github/macos_arm64/debug",

  # CircleCI static checks
  "ci/circleci: check_circular_deps",
  "ci/circleci: check_module_cmakelists",
  "ci/circleci: clang_format",
  "ci/circleci: cmake_format",
  "ci/circleci: inspect",
  "ci/circleci: python_format",
  "ci/circleci: shell_format",

  # CircleCI build and test
  "ci/circleci: configure_test_combinations",
  "ci/circleci: configure",
  "ci/circleci: core",
  "ci/circleci: tests.examples",
  "ci/circleci: tests.headers",
  "ci/circleci: tests.performance",
  "ci/circleci: tests.regressions",
  "ci/circleci: tests.unit",
  "ci/circleci: tests.unit.algorithms",
  "ci/circleci: tests.unit.container_algorithms",
  "ci/circleci: install",
  "ci/circleci: arm64_build",

  # Jenkins
  "jenkins/cscs-ault/hipcc-release",
  "jenkins/cscs-daint/cce-debug",
  "jenkins/cscs-daint/cce-release",
  "jenkins/cscs-daint/clang-11-debug",
  "jenkins/cscs-daint/clang-11-release",
  "jenkins/cscs-daint/clang-12-debug",
  "jenkins/cscs-daint/clang-12-release",
  "jenkins/cscs-daint/clang-13-debug",
  "jenkins/cscs-daint/clang-13-release",
  "jenkins/cscs-daint/clang-14-cuda-debug",
  "jenkins/cscs-daint/clang-14-cuda-release",
  "jenkins/cscs-daint/clang-15-debug",
  "jenkins/cscs-daint/clang-15-release",
  "jenkins/cscs-daint/gcc-9-debug",
  "jenkins/cscs-daint/gcc-9-release",
  "jenkins/cscs-daint/gcc-10-apex-debug",
  "jenkins/cscs-daint/gcc-10-apex-release",
  "jenkins/cscs-daint/gcc-11-debug",
  "jenkins/cscs-daint/gcc-11-release",
  "jenkins/cscs-daint/gcc-12-debug",
  "jenkins/cscs-daint/gcc-12-release",
  "jenkins/cscs-daint/gcc-cuda-debug",
  "jenkins/cscs-daint/gcc-cuda-release",
]
required_approvals = 0
delete_merged_branches = true
use_squash_merge = false
# Three hours to account for queueing delays
timeout_sec = 10800
