# Copyright (c) 2022 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

extensions = [
    "txt",
    "rst",
    "py",
    "cmake",
    "toml",
    "yml",
    "sh",
    "nix",
]

[copyright]
enable = true

[license]
enable = true
pattern = 'Boost[\s]+Software[\s]+License'

[spdx]
enable = true
pattern = 'BSL-1.0'

[pragma_once]
enable = false

[deprecated_includes]
enable = false

[deprecated_names]
enable = false

[disallowed_macros]
enable = false

[includes]
enable = false
